import { defineElement } from "@rikka/elements";
import { div, h1, h2, p, h3, ul, li, a } from "@rikka/dom";
import { showcasePageStyles, sharedStyles } from "../../shared/styles";

const BookmarkManager = defineElement("rikka-showcase-bookmark-manager", {
  styles: showcasePageStyles,
  render() {
    return div(
      { class: 'example-page' },
      h1({}, 'Bookmark Manager'),
      p({}, 'A "Read Later" app that teaches the canonical CRUD pattern in Rikka: reactive signals, computed derived views, effect-driven persistence, and modular Web Components.'),
      div({ class: 'showcase-hero' },
        h2({}, 'The Pattern: Signal → Compute → Effect'),
        p({}, 'Bookmark Manager follows the core reactive loop that you will use in almost every Rikka application. A ', sharedStyles.inlineCode('signal()'), ' holds your source-of-truth data. ', sharedStyles.inlineCode('computed()'), ' signals derive filtered or transformed views from that signal. And ', sharedStyles.inlineCode('effect()'), ' runs side effects — like writing to localStorage — whenever the data changes. The UI never manually triggers updates; it simply reads reactive values, and Rikka keeps everything in sync.'),
      ),
      h2({}, 'Key Features'),
      div({ class: 'feature-grid' },
        div({ class: 'feature-card' },
          h3({}, 'Reactive Signal State'),
          p({}, 'The bookmark array lives in a ', sharedStyles.inlineCode('signal()'), '. Because signals use immutable updates, operations like ', sharedStyles.inlineCode('bookmarks.set([...bookmarks.get(), newItem])'), ' or ', sharedStyles.inlineCode('bookmarks.set(bookmarks.get().map(...))'), ' create new arrays — Rikka tracks changes automatically.'),
        ),
        div({ class: 'feature-card' },
          h3({}, 'Computed Filtering'),
          p({}, 'Search text and selected tags are each a signal. A ', sharedStyles.inlineCode('computed()'), ' reads the bookmarks signal and both filter signals to produce a filtered bookmark list. When any input changes, the list recalculates and the DOM updates — no event wiring required.'),
        ),
        div({ class: 'feature-card' },
          h3({}, 'Effect-Driven Persistence'),
          p({}, 'An ', sharedStyles.inlineCode('effect()'), ' watches the signal state and writes it to ', sharedStyles.inlineCode('localStorage'), ' on every change. On startup, saved data is hydrated back into the signal. This "read-on-load, write-on-change" pattern is the standard way to add persistence in Rikka.'),
        ),
        div({ class: 'feature-card' },
          h3({}, 'Modular Web Components'),
          p({}, 'Each UI section — search bar, tag filter, bookmark form, bookmark list, bookmark item — is its own ', sharedStyles.inlineCode('defineElement()'), ' custom element with Shadow DOM. Components communicate through shared signals passed at creation time, keeping coupling low.'),
        ),
      ),
      h2({}, 'Data Flow'),
      div({ class: 'arch-section' },
        h3({}, 'How Data Moves Through the App'),
        ul({},
          li({}, sharedStyles.inlineCode('signal(bookmarks)'), ' ← source of truth; every update (add, edit, delete, mark-read) goes here'),
          li({}, sharedStyles.inlineCode('signal(searchQuery)'), ' + ', sharedStyles.inlineCode('signal(selectedTags)'), ' ← user input captured as signals'),
          li({}, sharedStyles.inlineCode('computed(filtered)'), ' ← reads the bookmarks signal + both filter signals → produces the visible bookmark list'),
          li({}, sharedStyles.inlineCode('computed(tagCloud)'), ' ← reads the bookmarks signal → produces the set of all tags with counts'),
          li({}, sharedStyles.inlineCode('effect(persist)'), ' ← reads the bookmarks signal → writes to localStorage on every change'),
          li({}, sharedStyles.inlineCode('For(filtered, ...)'), ' ← renders the filtered list reactively; items are added/removed as the computed value changes'),
        ),
      ),
      h2({}, 'Architecture'),
      div({ class: 'arch-section' },
        h3({}, 'Component Tree'),
        ul({},
          li({}, sharedStyles.inlineCode('bookmark-app'), ' — Root element. Owns the signals and filter signals, passes them to children.'),
          li({}, sharedStyles.inlineCode('search-bar'), ' — Text input that writes to the searchQuery signal.'),
          li({}, sharedStyles.inlineCode('tag-filter'), ' — Renders the tag cloud; clicking a tag toggles it in the selectedTags signal.'),
          li({}, sharedStyles.inlineCode('bookmark-form'), ' — Updates the bookmarks signal to add a new bookmark.'),
          li({}, sharedStyles.inlineCode('bookmark-list'), ' — Uses ', sharedStyles.inlineCode('For()'), ' over the computed filtered list.'),
          li({}, sharedStyles.inlineCode('bookmark-item'), ' — Reads one bookmark from the signal; edit/delete update the signal with immutable operations.'),
        ),
      ),
      div({ class: 'explanation' },
        h2({}, 'APIs Used'),
        p(sharedStyles.inlineCode('signal()'), ' — Creates a reactive container. Use it for arrays and objects that you update immutably (spread, map, filter).'),
        p(sharedStyles.inlineCode('computed()'), ' — Derives a read-only value from other reactive sources. Recalculates automatically when any source changes.'),
        p(sharedStyles.inlineCode('effect()'), ' — Runs a function whenever its reactive dependencies change. Used here for localStorage persistence.'),
        p(sharedStyles.inlineCode('defineElement()'), ' — Registers a custom element with a render function. Each element gets its own Shadow DOM.'),
        p(sharedStyles.inlineCode('For()'), ' — Reactive list rendering. Efficiently adds/removes DOM nodes as the list changes.'),
        p(sharedStyles.inlineCode('Show()'), ' — Conditional rendering. Displays the empty-state message when the filtered list is empty.'),
      ),
      div({ class: 'example-nav' },
        a({ href: '#/showcases', class: 'prev-link' }, '\u2190 Showcases'),
        div({ class: 'spacer' }),
        a({ href: '#/showcases/code-editor', class: 'next-link' }, 'Code Editor \u2192'),
      ),
    );
  }
});

export { BookmarkManager as ShowcaseBookmarkManager };
