import { defineElement } from "@takanashi/rikka-elements";
import { div, h1, h2, p, h3, ul, li, a } from "@takanashi/rikka-dom";
import {sharedHelpers} from "../../shared/helpers";
import {showcasePageStyles} from "../../shared/page-styles";

const CodeEditor = defineElement("rikka-showcase-code-editor", {
  styles: showcasePageStyles,
  render() {
    return div(
      { class: 'example-page' },
      h1({}, 'Code Editor'),
      p({}, 'A browser-based IDE that teaches you how to compose many reactive pieces — file system, tabs, preview, console, theming — into one cohesive application.'),
      div({ class: 'showcase-hero' },
        h2({}, 'The Pattern: One Signal, Many Derived Views'),
        p({}, 'Code Editor revolves around a single ', sharedHelpers.inlineCode('signal()'), ' that holds the virtual file system. From that one signal, multiple ', sharedHelpers.inlineCode('computed()'), ' signals derive the active file content, the combined preview HTML, and filtered console messages. ', sharedHelpers.inlineCode('effect()'), ' handles the side effects — writing into the iframe and intercepting console calls. This "single source of truth, many projections" pattern scales well as your app grows.'),
      ),
      h2({}, 'Key Features'),
      div({ class: 'feature-grid' },
        div({ class: 'feature-card' },
          h3({}, 'Reactive File System'),
          p({}, 'A ', sharedHelpers.inlineCode('signal()'), ' holds an array of file objects with name, type, and content. Opening a file, switching tabs, and editing content are all updates to this single signal — every UI section reacts to the same data.'),
        ),
        div({ class: 'feature-card' },
          h3({}, 'Tab System with Signals'),
          p({}, 'Open tabs are tracked in a ', sharedHelpers.inlineCode('signal([])'), ', and the active tab index in another ', sharedHelpers.inlineCode('signal(0)'), '. Closing a tab updates both signals. The tab bar, editor, and status bar all read from these signals, so they stay in sync automatically.'),
        ),
        div({ class: 'feature-card' },
          h3({}, 'Live iframe Preview'),
          p({}, 'A ', sharedHelpers.inlineCode('computed()'), ' combines the HTML, CSS, and JS from the signal into a single srcdoc string. An ', sharedHelpers.inlineCode('effect()'), ' writes that string into the iframe. Every keystroke propagates through the reactive chain and refreshes the preview — no manual refresh button needed.'),
        ),
        div({ class: 'feature-card' },
          h3({}, 'Theme Switching via CSS Custom Properties'),
          p({}, 'A theme signal drives ', sharedHelpers.inlineCode('CSS custom properties'), ' on the root element. All components read colors from these variables, so switching the signal value updates the entire UI reactively. This is the idiomatic way to implement theming in Rikka.'),
        ),
        div({ class: 'feature-card' },
          h3({}, 'Console Output Panel'),
          p({}, 'An ', sharedHelpers.inlineCode('effect()'), ' intercepts ', sharedHelpers.inlineCode('console.log'), ', ', sharedHelpers.inlineCode('console.error'), ', and ', sharedHelpers.inlineCode('console.warn'), ' inside the preview iframe. Messages are pushed into a reactive array and rendered with ', sharedHelpers.inlineCode('For()'), ' with color-coded levels — a practical example of cross-frame communication driven by reactivity.'),
        ),
      ),
      h2({}, 'Data Flow'),
      div({ class: 'arch-section' },
        h3({}, 'How Data Moves Through the App'),
        ul({},
          li({}, sharedHelpers.inlineCode('signal(files)'), ' ← source of truth for the file system; each file has name, type, content'),
          li({}, sharedHelpers.inlineCode('signal(openTabs)'), ' + ', sharedHelpers.inlineCode('signal(activeTab)'), ' ← which files are open and which is focused'),
          li({}, sharedHelpers.inlineCode('computed(activeFileContent)'), ' ← reads the files signal + activeTab → returns the content of the current file'),
          li({}, sharedHelpers.inlineCode('computed(previewSrcdoc)'), ' ← reads the files signal → combines all files into a single HTML document for the iframe'),
          li({}, sharedHelpers.inlineCode('effect(syncPreview)'), ' ← reads previewSrcdoc → writes it into the iframe\'s srcdoc attribute'),
          li({}, sharedHelpers.inlineCode('signal(consoleMessages)'), ' ← populated by the iframe intercept effect; rendered with ', sharedHelpers.inlineCode('For()')),
          li({}, sharedHelpers.inlineCode('signal(theme)'), ' ← drives CSS custom properties across all components'),
        ),
      ),
      h2({}, 'Architecture'),
      div({ class: 'arch-section' },
        h3({}, 'Component Tree'),
        ul({},
          li({}, sharedHelpers.inlineCode('editor-app'), ' — Root layout. Owns the files signal, tab signals, and theme signal.'),
          li({}, sharedHelpers.inlineCode('file-tree'), ' — Reads the files signal to render files and folders; clicking a file calls openFile().'),
          li({}, sharedHelpers.inlineCode('editor-tabs'), ' — Reads openTabs and activeTab signals; renders tab bar with close buttons.'),
          li({}, sharedHelpers.inlineCode('code-editor'), ' — Reads activeFileContent; writes edits back to the files signal.'),
          li({}, sharedHelpers.inlineCode('preview-panel'), ' — Contains the iframe; the syncPreview effect writes to it.'),
          li({}, sharedHelpers.inlineCode('console-panel'), ' — Reads consoleMessages signal; renders with ', sharedHelpers.inlineCode('For()'), '.'),
          li({}, sharedHelpers.inlineCode('theme-toggle'), ' — Writes to the theme signal; all components react through CSS custom properties.'),
        ),
      ),
      div({ class: 'explanation' },
        h2({}, 'APIs Used'),
        p(sharedHelpers.inlineCode('signal()'), ' — Reactive container for the file system. Supports nested structures (folders with children) via immutable updates.'),
        p(sharedHelpers.inlineCode('signal()'), ' — Lightweight reactive container for tab state, theme, and console messages. Use signal() for primitive or replace-by-value state.'),
        p(sharedHelpers.inlineCode('computed()'), ' — Derives the active file content, combined preview HTML, and language label from the files signal and other signals.'),
        p(sharedHelpers.inlineCode('effect()'), ' — Syncs the iframe preview on content change and intercepts iframe console calls. Effects are the bridge from reactive state to imperative APIs.'),
        p(sharedHelpers.inlineCode('defineElement()'), ' — Each panel and widget is an isolated custom element with its own Shadow DOM.'),
        p(sharedHelpers.inlineCode('For()'), ' — Reactive list rendering for tabs and console messages.'),
      ),
      div({ class: 'example-nav' },
        a({ href: '#/showcases/bookmark-manager', class: 'prev-link' }, '\u2190 Bookmark Manager'),
        div({ class: 'spacer' }),
        a({ href: '#/showcases/finance-tracker', class: 'next-link' }, 'Finance Tracker \u2192'),
      ),
    );
  }
});

export { CodeEditor as ShowcaseCodeEditor };
