import { defineElement } from "@takanashi/rikka-elements";
import { div, h1, h2, p, h3, ul, li, a } from "@takanashi/rikka-dom";
import {sharedHelpers} from "../../shared/helpers";
import {showcasePageStyles} from "../../shared/page-styles";

const FinanceTracker = defineElement("rikka-showcase-finance-tracker", {
  styles: showcasePageStyles,
  render() {
    return div(
      { class: 'example-page' },
      h1({}, 'Finance Tracker'),
      p({}, 'A finance dashboard that teaches Rikka\'s functional component style — building an entire app from plain functions and signals, without defineElement or Shadow DOM.'),
      div({ class: 'showcase-hero' },
        h2({}, 'The Pattern: Functions + Signals, No Classes'),
        p({}, 'Finance Tracker takes a different approach from the other showcases. Instead of ', sharedHelpers.inlineCode('defineElement()'), ', every UI section is a plain function that returns a DOM tree. Signals and computed values are created at the top level and passed into functions as arguments. This style is lighter weight, easier to test, and often more natural for application code that doesn\'t need the Web Component lifecycle or style encapsulation.'),
      ),
      h2({}, 'Key Features'),
      div({ class: 'feature-grid' },
        div({ class: 'feature-card' },
          h3({}, 'CRUD with Signal Updates'),
          p({}, 'Transactions live in a ', sharedHelpers.inlineCode('signal()'), '. Adding, editing, and deleting are done with immutable updates like spread and filter on the signal. Every update triggers reactive updates in the stats, chart, and list — no manual refresh.'),
        ),
        div({ class: 'feature-card' },
          h3({}, 'Computed Statistics'),
          p({}, 'Total income, total expenses, net balance, and per-category breakdowns are all ', sharedHelpers.inlineCode('computed()'), ' signals. They read the signal and recalculate automatically on every change. The stats bar and chart simply read these computed values — zero wiring code.'),
        ),
        div({ class: 'feature-card' },
          h3({}, 'Signal-Driven Bar Chart'),
          p({}, 'The category chart is pure CSS: each bar is a ', sharedHelpers.inlineCode('div'), ' whose width is bound to a computed category total. No chart library, no canvas — just reactive DOM elements. This pattern works for any simple visualization.'),
        ),
        div({ class: 'feature-card' },
          h3({}, 'Effect-Driven Persistence'),
          p({}, 'An ', sharedHelpers.inlineCode('effect()'), ' serializes the transaction signal value to JSON and writes to ', sharedHelpers.inlineCode('localStorage'), '. On startup, saved data is loaded back into the signal. The same "read-on-load, write-on-change" pattern as Bookmark Manager, applied here in the functional style.'),
        ),
        div({ class: 'feature-card' },
          h3({}, 'Functional Component Style'),
          p({}, 'Each UI section is a function like ', sharedHelpers.inlineCode('createTransactionForm(transactions, editingId)'), '. Signals are passed as arguments, not accessed through ', sharedHelpers.inlineCode('this'), ' or context. This makes components easy to reason about and test — just call the function and inspect the returned DOM.'),
        ),
      ),
      h2({}, 'Data Flow'),
      div({ class: 'arch-section' },
        h3({}, 'How Data Moves Through the App'),
        ul({},
          li({}, sharedHelpers.inlineCode('signal(transactions)'), ' ← source of truth; every CRUD operation updates this signal'),
          li({}, sharedHelpers.inlineCode('signal(editingId)'), ' + ', sharedHelpers.inlineCode('signal(filterCategory)'), ' ← UI state for which transaction is being edited and which category filter is active'),
          li({}, sharedHelpers.inlineCode('computed(totalIncome)'), ', ', sharedHelpers.inlineCode('computed(totalExpenses)'), ', ', sharedHelpers.inlineCode('computed(netBalance)'), ' ← aggregate stats derived from the signal'),
          li({}, sharedHelpers.inlineCode('computed(categoryTotals)'), ' ← per-category breakdown; drives both the stats display and the bar chart widths'),
          li({}, sharedHelpers.inlineCode('computed(filteredTransactions)'), ' ← reads the transactions signal + filterCategory signal → the visible list'),
          li({}, sharedHelpers.inlineCode('effect(persist)'), ' ← reads the transactions signal → writes to localStorage on every change'),
          li({}, sharedHelpers.inlineCode('For(filteredTransactions, ...)'), ' ← renders the list; items are added/removed as the computed value changes'),
        ),
      ),
      h2({}, 'Architecture'),
      div({ class: 'arch-section' },
        h3({}, 'Function Composition Tree'),
        ul({},
          li({}, sharedHelpers.inlineCode('createApp()'), ' — Root function. Creates the signals and all derived state, then composes child functions into a layout.'),
          li({}, sharedHelpers.inlineCode('createTransactionForm()'), ' — Add/edit form. Receives the transactions signal and editingId signal; writes updates on submit.'),
          li({}, sharedHelpers.inlineCode('createStatsBar()'), ' — Summary cards. Reads computed income, expenses, and net balance signals.'),
          li({}, sharedHelpers.inlineCode('createCategoryChart()'), ' — Horizontal bar chart. Reads computed categoryTotals; bar widths are bound to signal values.'),
          li({}, sharedHelpers.inlineCode('createTransactionList()'), ' — Uses ', sharedHelpers.inlineCode('For()'), ' over the computed filtered list; passes each item to createTransactionItem().'),
          li({}, sharedHelpers.inlineCode('createTransactionItem()'), ' — Single row. Reads one transaction from the signal; edit/delete update the signal with immutable operations.'),
        ),
      ),
      div({ class: 'explanation' },
        h2({}, 'APIs Used'),
        p(sharedHelpers.inlineCode('signal()'), ' — Reactive container for the transaction array. Updates (spread, filter, map) create new values that are tracked automatically.'),
        p(sharedHelpers.inlineCode('signal()'), ' — Holds UI-only state: the currently editing transaction ID, the active category filter, and form inputs.'),
        p(sharedHelpers.inlineCode('computed()'), ' — Derives totals, category breakdowns, and filtered views. All statistics are computed signals that recalculate when the signal changes.'),
        p(sharedHelpers.inlineCode('effect()'), ' — Auto-persists transactions to localStorage. The same pattern used in Bookmark Manager, but in a functional context.'),
        p(sharedHelpers.inlineCode('For()'), ' — Reactive list rendering for transactions. Items are added/removed as the filtered list changes.'),
        p(sharedHelpers.inlineCode('Show()'), ' — Conditional rendering for the empty state and the edit mode form.'),
      ),
      div({ class: 'example-nav' },
        a({ href: '#/showcases/code-editor', class: 'prev-link' }, '\u2190 Code Editor'),
        div({ class: 'spacer' }),
        a({ href: '#/showcases', class: 'next-link' }, 'Showcases \u2192'),
      ),
    );
  }
});

export { FinanceTracker as ShowcaseFinanceTracker };
