/**
 * @module node
 * Node.js adapter for rikka-site.
 *
 * Uses only the standard `node:http` module — no wrangler, no edge runtime.
 * If your project is bundled for the edge (Cloudflare Workers, Deno Deploy),
 * you can skip importing this file entirely.
 *
 * @example
 * ```ts
 * import { serve } from "@takanashi/rikka-site/node";
 * import { app } from "./resources.js";
 *
 * const server = serve(app, { port: 3000 });
 * server.ready.then(() => console.log(`on ${server.host}:${server.port}`));
 * ```
 */

import * as nodeHttp from "node:http";
import * as nodeFs from "node:fs";
import * as nodePath from "node:path";
import * as nodeUrl from "node:url";
import type { IncomingMessage, ServerResponse } from "node:http";
import type { Site } from "./site.js";
import type { HttpRequest, HttpResponse } from "./server.js";

export type { HttpResponse };

/**
 * Options for the Node adapter.
 */
export interface NodeHandlerOptions {
  /**
   * Port to listen on when using `serve()`.
   * Pass `0` to let the OS pick a free port — read it back via `server.port`.
   * @default 3000
   */
  port?: number;
  /**
   * Hostname to bind to. Use "0.0.0.0" to listen on all interfaces.
   * @default "127.0.0.1"
   */
  host?: string;
  /**
   * Base path prefix stripped from `req.url` before dispatch — useful when
   * the app is mounted behind a reverse proxy.
   * @example "/api"
   */
  basePath?: string;
  /**
   * SDK script source to serve at `/.well-known/sdk/sdk.js`.
   * When not provided, the adapter attempts to load it via the
   * `@takanashi/rikka-site/sdk` package export (which resolves to the built
   * `dist/sdk/sdk.js`). Set to `false` to disable SDK serving.
   */
  sdkScript?: string | false;
  /**
   * Called at the start of each request. If it returns an `HttpResponse`,
   * that response is sent immediately and the request never reaches the
   * Site. Useful for dev-only static file fallbacks.
   */
  before?(
    req: IncomingMessage,
    res: ServerResponse,
  ):
    | HttpResponse
    | undefined
    | void
    | Promise<HttpResponse | undefined | void>;
  /**
   * Post-process the response generated by the Site before it is written
   * back to the client. Useful for HTML enhancement or logging.
   */
  after?(
    response: HttpResponse,
    req: IncomingMessage,
  ): HttpResponse | Promise<HttpResponse>;
  /**
   * Called for every incoming request, before `before` and the Site handler.
   * Useful for request logging.
   */
  onRequest?(req: IncomingMessage): void;
  /**
   * Called once the server is listening. Receives the actual bound port and
   * host. If omitted, no startup message is printed.
   */
  onListen?(port: number, host: string): void;
}

// ---------------------------------------------------------------------------
// SDK loader
// ---------------------------------------------------------------------------

let _cachedSdk: string | null = null;

/**
 * Load the SDK bundle via the package export.
 * Caches the result after the first successful load.
 */
function loadSdkBundle(): string | null {
  if (_cachedSdk !== null) return _cachedSdk;
  try {
    // Resolve via the package export so it works whether this file is run from
    // src (tsx) or dist (built), as long as the SDK bundle has been built.
    const sdkUrl = import.meta.resolve("@takanashi/rikka-site/sdk");
    const distPath = nodeUrl.fileURLToPath(sdkUrl);
    _cachedSdk = nodeFs.readFileSync(distPath, "utf8");
    return _cachedSdk;
  } catch {
    return null;
  }
}

function isHttpResponse(value: unknown): value is HttpResponse {
  return (
    typeof value === "object" &&
    value !== null &&
    "status" in value &&
    "headers" in value &&
    "body" in value
  );
}

/**
 * Create a Node.js request listener (compatible with `http.createServer`).
 *
 * @example
 * ```ts
 * import { createServer } from "node:http";
 * import { createNodeHandler } from "@takanashi/rikka-site/node";
 * import { app } from "./resources.js";
 *
 * const server = createServer(createNodeHandler(app));
 * server.listen(3000);
 * ```
 */
export function createNodeHandler(
  site: Site,
  options: NodeHandlerOptions = {},
): (req: IncomingMessage, res: ServerResponse) => Promise<void> {
  const basePath = options.basePath ?? "";

  // Inject SDK script into Site options if not already set
  if (site.options.sdkScript === undefined && options.sdkScript !== false) {
    const sdkSource = options.sdkScript ?? loadSdkBundle();
    if (sdkSource) {
      site.options.sdkScript = sdkSource;
    }
  }

  return async (req, res) => {
    try {
      options.onRequest?.(req);

      const beforeResult = await options.before?.(req, res);
      if (isHttpResponse(beforeResult)) {
        writeNodeResponse(res, beforeResult);
        return;
      }

      const url = parseNodeUrl(req.url ?? "/", req.headers.host);
      const method = (req.method ?? "GET").toUpperCase();
      const headers = collectNodeHeaders(req.headers);
      const body = readNodeBodyStream(req, method);

      const httpRequest: HttpRequest = {
        method,
        path: stripBasePath(url.pathname, basePath) || "/",
        accept: headers["accept"],
        acceptQuery: url.searchParams.get("accept") ?? undefined,
        body,
        query: collectNodeQuery(url),
        headers,
      };

      let response = await site.handleRequest(httpRequest);
      if (options.after) {
        response = await options.after(response, req);
      }
      writeNodeResponse(res, response);
    } catch (err) {
      // Last-resort error handler — should not normally reach here.
      if (!res.headersSent) {
        res.statusCode = 500;
        res.setHeader("Content-Type", "text/plain");
      }
      res.end(err instanceof Error ? err.message : "Internal Server Error");
    }
  };
}

/**
 * Start an HTTP server and listen for connections.
 *
 * @example
 * ```ts
 * import { serve } from "@takanashi/rikka-site/node";
 * import { app } from "./resources.js";
 *
 * const server = serve(app, { port: 3000 });
 * console.log(`Listening on ${server.host}:${server.port}`);
 * ```
 */
export function serve(
  site: Site,
  options: NodeHandlerOptions = {},
): {
  /** Actual port (post-bind). May differ from options.port if 0 was used. */
  port: number;
  host: string;
  /** Stop accepting new connections; resolve when existing ones close. */
  close(): Promise<void>;
  /** The underlying http.Server instance. */
  server: nodeHttp.Server;
  /** Resolves once the server is actually listening. */
  ready: Promise<void>;
} {
  const requestedPort = options.port ?? 3000;
  const host = options.host ?? "127.0.0.1";
  const handler = createNodeHandler(site, options);
  const server = nodeHttp.createServer(handler);

  let actualPort = requestedPort;
  const ready = new Promise<void>((resolve) => {
    server.once("listening", () => {
      const addr = server.address();
      if (addr && typeof addr === "object") actualPort = addr.port;
      options.onListen?.(actualPort, host);
      resolve();
    });
  });
  server.listen(requestedPort, host);

  return {
    get port() {
      return actualPort;
    },
    host,
    server,
    ready,
    close() {
      return new Promise<void>((resolve, reject) => {
        server.close((err) => (err ? reject(err) : resolve()));
      });
    },
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function parseNodeUrl(rawUrl: string, hostHeader: string | string[] | undefined): URL {
  const host = Array.isArray(hostHeader) ? hostHeader[0] : hostHeader;
  if (/^https?:\/\//i.test(rawUrl)) return new URL(rawUrl);
  return new URL(rawUrl, `http://${host ?? "localhost"}`);
}

function stripBasePath(pathname: string, basePath: string): string {
  if (!basePath) return pathname;
  if (pathname === basePath) return "/";
  if (pathname.startsWith(basePath + "/")) return pathname.slice(basePath.length);
  return pathname;
}

function collectNodeHeaders(
  raw: NodeJS.Dict<string | string[] | undefined>,
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(raw)) {
    if (value === undefined) continue;
    out[key.toLowerCase()] = Array.isArray(value) ? value.join(", ") : value;
  }
  return out;
}

function collectNodeQuery(url: URL): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [key, value] of url.searchParams.entries()) {
    if (key !== "accept") out[key] = value;
  }
  return out;
}

/**
 * Convert a Node.js `IncomingMessage` into a Web `ReadableStream<Uint8Array>`.
 *
 * Returns `undefined` for GET/HEAD requests (no body). The stream is
 * lazily consumed — if the handler never calls `ctx.json()` / `ctx.text()`
 * / `ctx.bytes()`, the request body is never read.
 */
function readNodeBodyStream(
  req: IncomingMessage,
  method: string,
): ReadableStream<Uint8Array> | undefined {
  if (method === "GET" || method === "HEAD") return undefined;

  return new ReadableStream<Uint8Array>({
    start(controller) {
      req.on("data", (chunk: Buffer | string) => {
        const bytes =
          typeof chunk === "string"
            ? new TextEncoder().encode(chunk)
            : new Uint8Array(chunk.buffer, chunk.byteOffset, chunk.byteLength);
        controller.enqueue(bytes);
      });
      req.on("end", () => controller.close());
      req.on("error", (err) => controller.error(err));
    },
  });
}

/**
 * Write an {@link HttpResponse} to a Node.js `ServerResponse`.
 *
 * Handles all three body shapes:
 * - `string` / `Uint8Array` — written directly via `res.end()`
 * - `ReadableStream<Uint8Array>` — piped chunk-by-chunk, then `res.end()`
 */
function writeNodeResponse(
  res: ServerResponse,
  response: HttpResponse,
): void {
  res.statusCode = response.status;
  for (const [key, value] of Object.entries(response.headers)) {
    res.setHeader(key, value);
  }

  const body = response.body;

  if (typeof body === "string" || body instanceof Uint8Array) {
    res.end(body);
    return;
  }

  // Stream — pipe chunk by chunk
  const reader = body.getReader();
  const pump = (): void => {
    reader
      .read()
      .then(({ done, value }) => {
        if (done) {
          res.end();
          return;
        }
        if (value) res.write(value);
        pump();
      })
      .catch((err) => {
        if (!res.headersSent) {
          res.statusCode = 500;
        }
        res.end(err instanceof Error ? err.message : "Stream error");
      });
  };
  pump();
}
