export { For, applyChild, insertChildBefore, ReactiveRange, createElement, registerDisposable } from "./h.js";
export type {
  Child,
  Attributes,
  ElementTagNameMap,
  TagFunction,
} from "./h.js";
export type {
  AttrValue,
  StyleValue,
  StyleRecord,
  StyleAttr,
  GlobalHTMLAttributes,
  AriaAttributes,
  DataAttributes,
  CommonHTMLAttributes,
  AttrTagNameMap,
  AnchorHTMLAttributes,
  AreaHTMLAttributes,
  AudioHTMLAttributes,
  BaseHTMLAttributes,
  BlockquoteHTMLAttributes,
  ButtonHTMLAttributes,
  CanvasHTMLAttributes,
  ColHTMLAttributes,
  ColgroupHTMLAttributes,
  DataHTMLAttributes,
  DetailsHTMLAttributes,
  DialogHTMLAttributes,
  EmbedHTMLAttributes,
  FieldsetHTMLAttributes,
  FormHTMLAttributes,
  HrHTMLAttributes,
  IframeHTMLAttributes,
  ImgHTMLAttributes,
  InputHTMLAttributes,
  LabelHTMLAttributes,
  LiHTMLAttributes,
  LinkHTMLAttributes,
  MapHTMLAttributes,
  MediaHTMLAttributes,
  MenuHTMLAttributes,
  MetaHTMLAttributes,
  MeterHTMLAttributes,
  ObjectHTMLAttributes,
  OlHTMLAttributes,
  OptgroupHTMLAttributes,
  OptionHTMLAttributes,
  OutputHTMLAttributes,
  ProgressHTMLAttributes,
  QuoteHTMLAttributes,
  ScriptHTMLAttributes,
  SelectHTMLAttributes,
  SourceHTMLAttributes,
  StyleHTMLAttributes,
  TableHTMLAttributes,
  TdHTMLAttributes,
  TextareaHTMLAttributes,
  ThHTMLAttributes,
  TimeHTMLAttributes,
  TrackHTMLAttributes,
  VideoHTMLAttributes,
  SVGAttributes,
  MathMLAttributes,
} from "./attributes.js";
export { Show, When, Switch, Match } from "./control-flow.js";
export type { Case } from "./control-flow.js";
export { css, inlineStyle } from "./template.js";
export {
  h,
  div,
  span,
  a,
  p,
  button,
  input,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  section,
  article,
  aside,
  nav,
  header,
  footer,
  main,
  ul,
  ol,
  li,
  table,
  thead,
  tbody,
  tr,
  th,
  td,
  form,
  select,
  option,
  label,
  textarea,
  pre,
  code,
  br,
  hr,
  img,
  slot,
  template,
  svg,
  circle,
  path,
  rect,
  line,
  polygon,
  polyline,
  g,
  defs,
  use,
  foreignObject,
  clipPath,
  pattern,
  marker,
  mask,
  image,
  linearGradient,
  radialGradient,
  stop,
  symbol,
  filter,
  ellipse,
  svga,
  svgscript,
  svgstyle,
  svgtitle,
  svgtext,
  svgspan,
  svgtextPath,
} from "./tags.js";
export type { H } from "./tags.js";

import { h } from "./tags.js";
export default h;
