import type { Locale } from './i18n';

export const content = {
  appTitle: { en: '🍅 Pomodoro Timer', zh: '🍅 番茄钟' },
  appSubtitle: { en: 'Focus on work, rest efficiently', zh: '专注工作，高效休息' },
  start: { en: 'Start', zh: '开始' },
  pause: { en: 'Pause', zh: '暂停' },
  reset: { en: 'Reset', zh: '重置' },
  completed: { en: 'Completed: ', zh: '已完成: ' },
  pomodoros: { en: ' pomodoros', zh: ' 个番茄' },
  focus: { en: 'Focus', zh: '专注' },
  shortBreak: { en: 'Short Break', zh: '短休息' },
  longBreak: { en: 'Long Break', zh: '长休息' },
  // --- 任务相关 ---
  tasks: { en: 'Tasks', zh: '任务' },
  addTask: { en: 'Add a task...', zh: '添加任务...' },
  addTaskBtn: { en: 'Add', zh: '添加' },
  estimateLabel: { en: 'Estimate (pomodoros)', zh: '预计（番茄数）' },
  activeTask: { en: 'Active Task', zh: '当前任务' },
  noActiveTask: { en: 'Select a task to focus on', zh: '选择一个任务专注' },
  noTasks: { en: 'No tasks yet. Add one above!', zh: '暂无任务，先添加一个吧！' },
  completedTasks: { en: 'Completed', zh: '已完成' },
  clearCompleted: { en: 'Clear Completed', zh: '清除已完成' },
  // --- 统计相关 ---
  today: { en: 'Today', zh: '今日' },
  total: { en: 'Total', zh: '总计' },
  streak: { en: 'Day Streak', zh: '连续天数' },
  weeklyOverview: { en: 'Weekly Overview', zh: '本周概览' },
  // --- 设置相关 ---
  settings: { en: 'Settings', zh: '设置' },
  pomodoroLength: { en: 'Pomodoro (min)', zh: '专注时长（分钟）' },
  shortBreakLength: { en: 'Short Break (min)', zh: '短休息（分钟）' },
  longBreakLength: { en: 'Long Break (min)', zh: '长休息（分钟）' },
  longBreakEvery: { en: 'Long Break Every', zh: '长休息间隔' },
  autoStartBreak: { en: 'Auto start break', zh: '自动开始休息' },
  autoStartPomodoro: { en: 'Auto start focus', zh: '自动开始专注' },
  soundEnabled: { en: 'Sound notifications', zh: '声音提示' },
  resetSettings: { en: 'Reset to defaults', zh: '恢复默认设置' },
  close: { en: 'Close', zh: '关闭' },
} satisfies Record<string, Record<Locale, string>>;
