export const content = {
  appTitle: { en: '💰 Personal Finance Tracker', zh: '💰 个人财务追踪' },
  recentTransactions: { en: 'Recent Transactions', zh: '最近交易' },
  expenseBreakdown: { en: 'Expense Breakdown', zh: '支出分布' },
  noExpenseData: { en: 'No expense data', zh: '暂无支出数据' },
  addExpensesToSee: { en: 'Add expenses to see breakdown', zh: '添加支出后查看分布' },
  totalBalance: { en: 'Total Balance', zh: '总余额' },
  monthIncome: { en: 'This Month Income', zh: '本月收入' },
  monthExpenses: { en: 'This Month Expenses', zh: '本月支出' },
  addIncome: { en: '+ Add Income', zh: '+ 添加收入' },
  addExpense: { en: '+ Add Expense', zh: '+ 添加支出' },
  amount: { en: 'Amount', zh: '金额' },
  type: { en: 'Type', zh: '类型' },
  income: { en: 'Income', zh: '收入' },
  expense: { en: 'Expense', zh: '支出' },
  category: { en: 'Category', zh: '类别' },
  date: { en: 'Date', zh: '日期' },
  description: { en: 'Description', zh: '描述' },
  descPlaceholder: { en: 'What was this for?', zh: '这笔钱花在哪里了？' },
  noDescription: { en: 'No description', zh: '无描述' },
  deleteTransaction: { en: 'Delete transaction', zh: '删除交易' },
  noTransactions: { en: 'No transactions yet', zh: '暂无交易' },
  addFirst: { en: 'Add your first transaction above', zh: '在上方添加你的第一笔交易' },
  // Category names
  catFood: { en: 'Food', zh: '食物' },
  catTransport: { en: 'Transport', zh: '交通' },
  catEntertainment: { en: 'Entertainment', zh: '娱乐' },
  catShopping: { en: 'Shopping', zh: '购物' },
  catBills: { en: 'Bills', zh: '账单' },
  catSalary: { en: 'Salary', zh: '工资' },
  catOther: { en: 'Other', zh: '其他' },
};
