export const content = {
  appTitle: { en: '💻 Code Editor', zh: '💻 代码编辑器' },
  appSubtitle: { en: 'HTML, CSS, JavaScript Online Editor', zh: 'HTML, CSS, JavaScript 在线编辑器' },
  resetCode: { en: 'Reset Code', zh: '重置代码' },
  htmlPlaceholder: { en: 'Write HTML here...', zh: '在这里编写 HTML...' },
  cssPlaceholder: { en: 'Write CSS here...', zh: '在这里编写 CSS...' },
  jsPlaceholder: { en: 'Write JavaScript here...', zh: '在这里编写 JavaScript...' },
  consoleEmpty: { en: 'Console is empty, waiting for output...', zh: '控制台为空，等待输出...' },
  clearConsole: { en: 'Clear', zh: '清空' },
  consoleTitle: { en: '🖥️ Console', zh: '🖥️ 控制台' },
  refresh: { en: 'Refresh', zh: '刷新' },
  console: { en: 'Console', zh: '控制台' },
  preview: { en: '👁️ Preview', zh: '👁️ 预览' },
  confirmReset: { en: 'Are you sure you want to reset all code? This cannot be undone.', zh: '确定要重置所有代码吗？这将无法撤销。' },
  // Default code content
  previewTitle: { en: 'Preview', zh: '预览' },
  defaultDesc: { en: 'This is a live editor, modify the code below to see results', zh: '这是一个实时编辑器，修改下方代码即可看到效果' },
  clickMe: { en: 'Click me', zh: '点击我' },
  clickCount: { en: 'Click count: ', zh: '点击次数: ' },
  btnClicked: { en: 'Button clicked ', zh: '按钮被点击了 ' },
  times: { en: ' times!', zh: ' 次！' },
  great5: { en: "🎉 Great! You've clicked 5 times!", zh: '🎉 太棒了！你已经点击了5次！' },
  warning10: { en: '⚠️ Warning: You\'ve clicked 10 times, take a break!', zh: '⚠️ 警告：你已经点击10次了，休息一下吧！' },
  editorReady: { en: '🚀 Editor is ready! Start editing code', zh: '🚀 编辑器已就绪！开始编辑代码吧' },
};
